# Dockerfile.frontend

# Use the official Node.js 18-alpine image as base
FROM node:20-alpine

# Set work directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./cmx-battleship/package*.json /app/

# Install dependencies
RUN npm ci

# Copy the frontend source code
COPY ./cmx-battleship /app

# Expose the frontend port
EXPOSE 4200

# Command to run the frontend server
CMD ["npm", "run", "start:docker"]
