services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./cmx-battleship-online-api:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://battleship_app_role:password@db:5432/battleship_app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    volumes:
      - ./cmx-battleship:/app
      # prevent overwrite which causes red herring: https://github.com/npm/cli/issues/4828
      - /app/node_modules
      - /dev/null:/app/package-lock
    environment:
      - HOST=0.0.0.0

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: battleship_app
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: